### ISSUE TITLE
issue with view:cach artisan command

### ISSUE THREAD

**Issue by imami** [zeeshantariq08/filament-attachmate#3]
Using Laravel 11 with `zeeshantariq/filament-attachmate` version 1.1,
When I run `php artisan view:cach` in my Laravel project, I got this error:
```
The "vendor/zeeshantariq/filament-attachmate/src/../resources/views" directory does not exist.

  at vendor/symfony/finder/Finder.php:646
    642▕             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? \GLOB_BRACE : 0) | \GLOB_ONLYDIR | \GLOB_NOSORT)) {
    643▕                 sort($glob);
    644▕                 $resolvedDirs[] = array_map($this->normalizeDir(...), $glob);
    645▕             } else {
  ➜ 646▕                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    647▕             }
    648▕         }
    649▕ 
    650▕         $this->dirs = array_merge($this->dirs, ...$resolvedDirs);

      +17 vendor frames 

  18  artisan:13
      Illuminate\Foundation\Application::handleCommand()
```
which is related to this `->hasViews()` in [FilamentAttachmateServiceProvider.php](https://github.com/zeeshantariq08/filament-attachmate/blob/ed46d3850ed1d834539d8c08832c9444a348cf75/src/FilamentAttachmateServiceProvider.php#L19)

@zeeshantariq08

**Comment by imami** [comment]
since It seems you don't have any views in your package, maybe this `hasViews()` is not only useless, but also causes this issue with the whole project using it.

**Comment by zeeshantariq08** [comment]
i have resolved the issue , thank you
